### ISSUE TITLE
Module 1: Feedback on slides for module 1 

### ISSUE THREAD

**Issue by hfboyce** [UBC-MDS/MCL-DSCI-011-programming-in-python#14]
Please ignore last 2 exercise solutions!!

**Comment by mgelbart** [comment]
@hfboyce can you please include a link to where we should look at the slides?

**Comment by hfboyce** [comment]
AHHHH sorry!! [Here](https://mcl-dsci-511-programming-in-python.netlify.com/)!!

**Comment by mgelbart** [comment]
Comments, numbered by sub-module:

## 0

LGTM

## 1

- As a general philosophy, I like to start with the problem before introducing the solution. Thus, I'd start by introducing the idea of tabular data, and how it's ubiquitous, before introducing the solution (pandas). 
- I think 1 slide worth of pandas puns is enough. Maybe remove the GIF and keep the 2nd one.
- The idea that `pandas` is an add-on to Python is not immediately essential, and may not make sense given their (lack of) mental model about the whole ecosystem. I prefer such things to go at the end. It all comes back to [this](https://ubc-mds.github.io/2017-11-10-DSCI-542-communication/).
- Please don't spend too long on this, but is there an easy way to enable slide numbers? For feedback purposes it would be useful. Right now we have module --> sub-module (is there a better name?) --> slide, but the last one is not numbered.
- Reading in data: they don't yet know what a "dataframe" is. 
- Output table is too small to read.
- Do we first need to introduce the idea of a line of code? What prerequisite knowledge are we assuming? Maybe we at least need to say the code is in light gray and the output is in the dark gray/black background?
- `print(df.shape)`: I guess the `print` statements are going away?
- `length` vs. `len` typo
- I think it's not worth it to introduce functions vs. methods so early. Again, a main principle is to keep it as simple as possible for as long as possible. `len` isn't very important since we already have `df.shape`.
- Some copy editing needed; missing capitalization, line breaks, etc. (same for other sections, but i won't keep mentioning it)

## 2-4

- Should we also be giving feedback on the exercises? I'm a bit confused by the Issue title, which says slides. Let me know if they are ready and I'll happily review the rest.

## 5

- "Now the index has been set as the name of the cereal (we will talk about how to do this later)", ah, I guess this still needs to be fixed.
- The output is too small to read on the above slide.
- It's -> Its
- "So it's important that we relearn counting from childhood to include 0." -> delete this
- "Perhaps we were only interested in the calories to fiber columns of those rows?" -> needs an exercise after this. I think we already discussed this?
- I'm going to stop reviewing this section for now because I think we talked about it and there are pending changes (is that right?).
- BTW, do they know what a .csv file is? Should we tell them? Should we show them the raw CSV at some point? I'm not sure we should - just a thought.

## 9

- "We can also reorder it too to change the column and row order." I think when you have something like this it really lends itself to a quick exercise. Even just a multiple choice asking "which line of code would lead to the output below" and showing different orderings. You have that as the next slide instead - I think an exercise is better.

## 12

- Maybe the "i" in `iloc` refers to "integer" ?
- A general comment that can apply everywhere: there is a pattern where you show the whole df, and then on the _next_ slide you say what we want to accomplish, e.g. "Let's say we want the rows All-Bran to Apple Cinnamon Cheerios but we want to slice based on their position." When I read that sentence I really want to be looking at the printed out dataframe so I can internalize exactly what it is we're trying to accomplish. But at this point I'm already on the next slide that shows the _answer_. So, I would move more of these problem statements to the earlier slide that also shows the df. Think about reading this sentence "Using Python's counting method of starting at zero, we conclude All-Bran to be at position to 2." while looking at that slide. It doesn't quite make sense because that slide is already showing the slice where it's at position 0.

## 16

- `df.describe(include = "all")` -> have they seen arguments before?
- "Some of these might produce some wild results especially if the column is a qualitative observation." hmm... maybe avoid this for now by showing the sum of one (or a subset of) columns?
- The `pd.value_counts` slide is confusing. 1) we should be careful & consistent about writing `pd.value_counts` vs `pd.value_counts()`. Not sure what is best.  2) The slide doesn't actually call `pd.value_counts()` and show the output, which confused me. 
- "We can also use the argument sort = True withing the brackets if we want to sort the categories in frequency order" -> let's be careful 
- "This looks a bit funny though doesn't it?" -> Let's be deliberate about when we introduce Series. Is this the right time? It may well be. But if so we should introduce it properly. I think the lesson as it stands may be confusing. We haven't introduced the idea of a data type yet. One possible solution is just to leave it printed as a Series and hope they don't notice it looks different. But if so we'll have to move the column renaming to somewhere else. Oh I see, but you also use it in part 20.  Hmm... but maybe all that stuff would work fine with a Series? Or ... I don't know. Open to ideas here. 
- "curley" -> "curly"

## 20

- "It is a good idea to save it as an object too, let's call it brand_plot" -> does the plot actually show in Jupyter if you save it as an object, or only if you don't?
- I could not actually see a size different after you set `s` in the plot. Maybe set it to something more drastic so the change is obvious?
- This is a fun section - it's great that pandas provides these plotting tools. 

## Overall

- Please go through everything and fix the punctuation / grammar / spelling / etc before starting the review process. The errors are a bit distracting to the review process.
- Please resolve the reproducibility issue before implementing my changes. I think it would be wasteful to create more images and then delete them again, etc. 
- Sorry, all of the above might sound a bit harsh. You're doing a great job @hfboyce 🌟 . I'm trusting what you said earlier that you want to hear all the feedback that comes to mind!

**Comment by mgelbart** [comment]
# Feedback on exercises:

## 2

- Let's be consistent between "data frame" vs. "dataframe" vs. "Dataframe" vs "DataFrame"
- What is pandas: I'd drop the pun here, I think it's a bit much. Also, they might not know what a Python package is. How about "A useful tool for data manipulation in Python" ?

## 3

- The "Run Code" button looks greyed out - if it's easy to change, can we change it a bit to make it clear that it's pressable?

## 4

- It could be confusing that they have to delete the `#` in `# ____ ` - this was not needed in the previous one. This should be an instruction, or maybe you plan to split them into separate cells and we won't need the `#` anyway?

## 6

- Capitalization error "my" -> "My"
- I feel like we may have discussed this one in person. In any case, I think we should really show the printed df here instead of describing it. 
- It may be good to have a distractor (wrong answer) that goes one column too far, in case something think it's exclusive on the end point?

## 7

- Let's be careful with terminology like "database". Should we stick to "data set" (or "dataset")?
- This is really no doable without being able to look at the df. Maybe it could be printed out by the code, and then they write more code, or something?

## 8

- It's a bit confusing that both this and the one from (7) are canucks.csv but they are different. I would point out the change in `index_col` so they understand why it's different.
- Typo: he -> the


## 10

- Just curious, why the hint? It is possible with `loc` as well.
- typo: The -> the
- typo: `Weight.` -> `Weight`
- One of the lines is too long, causing scrolling. Let's try to avoid that? We can just spread the comment onto multiple lines.
- The solution is also a long line. Should we show them how to do it across lines? Maybe it's actually a bad idea, since the rules on when it's ok / not ok aren't that straightforward. 
- Any particular reason for the `##` instead of `#` in one case?

## 11

- Maybe this is a bit too repetitive?

## 13

- Again, we should show the df.
- Not a big deal but I only had to look at the rows to get the right answer, since only one of the 4 choices had the correct row query (for Question 1).
- Typo: indec -> index
- Formatting: `[0 ,6 ,2]` should be [0, 6, 2]`

## 14

- This is actually fairly confusing: the difference between using `loc` _when the index is integers anyway` vs. using `iloc`. My first reaction to this exercise was, but we already did it with integer indexing! I think we should maybe emphasize this distinction more overall. Maybe we can have an exercise where you have integer indexing and you show that `loc` and `iloc` do the exact same thing? And then maybe another exercise where you have integer indexes but they are not in order (e.g. you sorted the df by some column first) and so then `loc` and `iloc` do different things? These both seem valuable to get at small distinctions. 
- In general, it feels a bit repetitive to do the same exercise 3 times: loc with names, loc with integers, and then iloc with integers.

## 15

- Typo: "various form of injuries"
- Grammar: change comma to period or semicolon before "let's select"
- Typo: missing question mark in hint.

## 17

- Spelling: "occurances". Run spell check?
- I find the "X" thing is confusing, I'd just show the entire thing with `pd.value_counts` in each case. 

## 18

- What do you mean by "most prominent country" ? Most frequent? Should we also teach them how to get this programmatically? By not doing so, might we be creating some bad habits with this exercise? 

## 19

- "in lecture" -> maybe not the right terminology here
- typo: let -> let's
- Note that `sort=True` seems to be the default for `value_counts()`, so no need to specify it
- Again going back to habits, and I don't know the right answer here, but we should consider: do we want them making temp variables all the time like `position_column`? As opposed to `hockey_players["Position"].value_counts(sort = True)`? Maybe we should show them both? Or maybe you're planning for that later in the course? I'm not sure what is the best approach here.

## 21

- I might prefer to have it load canucks.csv and then copy in the couple of lines of code that computes the `position_freq_df` from there. But I don't feel strongly. 
- In the solution, there is no need to have `position_bar` at the end. In fact we should avoid it, because it causes `<matplotlib.axes._subplots.AxesSubplot at 0x7f6460b13810>` to print out, which we don't want. 
- In fact, there is no need to save the plot as an object at all. However, doing so does suppress the printing, which is kind of nice; if we did not save the plot as an object then we'd need to end the line with a `;` to suppress it. Not sure what is best? But I think we should pick an approach that suppresses the printout.

## 22

- typo: extra `.` before 'using"
- should we consider having them divide by 1_000_000 and then labeling the y axis as "Salary (millions)" ? They might not notice, or might be confused by, the little `1e6` and the fact that the salaries seem so low.

General question/comment: are we working on splitting up these into smaller "cells"? And, if so, would it be possible to show solution for only one of the "cells"? That would be super useful, I think - to show the solution to one line on a multi-line exercise. I think being able to split things up would be a huge improvement to the learning experience of these exercises. It means you could also print out the result of your first line of code before starting the next line.

This is looking good - keep it up @hfboyce !

**Comment by hfboyce** [comment]
# Addressing Feedback and changes made 

Comments, numbered by sub-module:

## 0
> LGTM

I had to google what this acronym was and now I am informed! 

## 1

> As a general philosophy, I like to start with the problem before introducing the solution. Thus, I'd start by introducing the idea of tabular data, and how it's ubiquitous, before introducing the solution (pandas). 

I added 2 slides explaining what a dataframe is a bit better from Tiffany's lecture 

> - I think 1 slide worth of pandas puns is enough. Maybe remove the GIF and keep the 2nd one.

Taken out! 

> The idea that `pandas` is an add-on to Python is not immediately essential, and may not make sense given their (lack of) mental model about the whole ecosystem. I prefer such things to go at the end. It all comes back to [this](https://ubc-mds.github.io/2017-11-10-DSCI-542-communication/).

I have completely taken out any information to do with "adding on" pandas and simply say we need to import this to analyze dataframes. 

> - Please don't spend too long on this, but is there an easy way to enable slide numbers? For feedback purposes it would be useful. Right now we have module --> sub-module (is there a better name?) --> slide, but the last one is not numbered.

- They are ugly but done! 

> Reading in data: they don't yet know what a "dataframe" is. 
I have added 2 slide from Tiffany's lecture explaining dataframes so this should address this? 

> - Output table is too small to read.

Should get fixed with the new rendering.

> - Do we first need to introduce the idea of a line of code? What prerequisite knowledge are we assuming? Maybe we at least need to say the code is in light gray and the output is in the dark gray/black background?

Added this to slide 5.

> - `print(df.shape)`: I guess the `print` statements are going away?

Gone! 
> - `length` vs. `len` typo

Done

> - I think it's not worth it to introduce functions vs. methods so early. Again, a main principle is to keep it as simple as possible for as long as possible. `len` isn't very important since we already have `df.shape`.

I've taken out length. This we be edited for all the follow up exercises and assignment too. 

> - Some copy editing needed; missing capitalization, line breaks, etc. (same for other sections, but i won't keep mentioning it)

Run through grammarly and word! 

## 5 I AM HERE 

- "Now the index has been set as the name of the cereal (we will talk about how to do this later)", ah, I guess this still needs to be fixed.
- The output is too small to read on the above slide.
- It's -> Its
- "So it's important that we relearn counting from childhood to include 0." -> delete this
- "Perhaps we were only interested in the calories to fiber columns of those rows?" -> needs an exercise after this. I think we already discussed this?
- I'm going to stop reviewing this section for now because I think we talked about it and there are pending changes (is that right?).
- BTW, do they know what a .csv file is? Should we tell them? Should we show them the raw CSV at some point? I'm not sure we should - just a thought.

## 9

- "We can also reorder it too to change the column and row order." I think when you have something like this it really lends itself to a quick exercise. Even just a multiple choice asking "which line of code would lead to the output below" and showing different orderings. You have that as the next slide instead - I think an exercise is better.

## 12

- Maybe the "i" in `iloc` refers to "integer" ?
- A general comment that can apply everywhere: there is a pattern where you show the whole df, and then on the _next_ slide you say what we want to accomplish, e.g. "Let's say we want the rows All-Bran to Apple Cinnamon Cheerios but we want to slice based on their position." When I read that sentence I really want to be looking at the printed out dataframe so I can internalize exactly what it is we're trying to accomplish. But at this point I'm already on the next slide that shows the _answer_. So, I would move more of these problem statements to the earlier slide that also shows the df. Think about reading this sentence "Using Python's counting method of starting at zero, we conclude All-Bran to be at position to 2." while looking at that slide. It doesn't quite make sense because that slide is already showing the slice where it's at position 0.

## 16

- `df.describe(include = "all")` -> have they seen arguments before?
- "Some of these might produce some wild results especially if the column is a qualitative observation." hmm... maybe avoid this for now by showing the sum of one (or a subset of) columns?
- The `pd.value_counts` slide is confusing. 1) we should be careful & consistent about writing `pd.value_counts` vs `pd.value_counts()`. Not sure what is best.  2) The slide doesn't actually call `pd.value_counts()` and show the output, which confused me. 
- "We can also use the argument sort = True withing the brackets if we want to sort the categories in frequency order" -> let's be careful 
- "This looks a bit funny though doesn't it?" -> Let's be deliberate about when we introduce Series. Is this the right time? It may well be. But if so we should introduce it properly. I think the lesson as it stands may be confusing. We haven't introduced the idea of a data type yet. One possible solution is just to leave it printed as a Series and hope they don't notice it looks different. But if so we'll have to move the column renaming to somewhere else. Oh I see, but you also use it in part 20.  Hmm... but maybe all that stuff would work fine with a Series? Or ... I don't know. Open to ideas here. 
- "curley" -> "curly"

## 20

- "It is a good idea to save it as an object too, let's call it brand_plot" -> does the plot actually show in Jupyter if you save it as an object, or only if you don't?
- I could not actually see a size different after you set `s` in the plot. Maybe set it to something more drastic so the change is obvious?
- This is a fun section - it's great that pandas provides these plotting tools. 

## Overall

- Please go through everything and fix the punctuation / grammar / spelling / etc before starting the review process. The errors are a bit distracting to the review process.
- Please resolve the reproducibility issue before implementing my changes. I think it would be wasteful to create more images and then delete them again, etc. 
- Sorry, all of the above might sound a bit harsh. You're doing a great job @hfboyce 🌟 . I'm trusting what you said earlier that you want to hear all the feedback that comes to mind!

**Comment by hfboyce** [comment]
# Addressing Feedback on exercises:

## 3

> [ ] The "Run Code" button looks greyed out - if it's easy to change, can we change it a bit to make it clear that it's pressable?

Adding to the list

## 4

- It could be confusing that they have to delete the `#` in `# ____ ` - this was not needed in the previous one. This should be an instruction, or maybe you plan to split them into separate cells and we won't need the `#` anyway?

## 6

- Capitalization error "my" -> "My"
- I feel like we may have discussed this one in person. In any case, I think we should really show the printed df here instead of describing it. 
- It may be good to have a distractor (wrong answer) that goes one column too far, in case something think it's exclusive on the end point?

## 7

- Let's be careful with terminology like "database". Should we stick to "data set" (or "dataset")?
- This is really no doable without being able to look at the df. Maybe it could be printed out by the code, and then they write more code, or something?

## 8

- It's a bit confusing that both this and the one from (7) are canucks.csv but they are different. I would point out the change in `index_col` so they understand why it's different.
- Typo: he -> the


## 10

- Just curious, why the hint? It is possible with `loc` as well.
- typo: The -> the
- typo: `Weight.` -> `Weight`
- One of the lines is too long, causing scrolling. Let's try to avoid that? We can just spread the comment onto multiple lines.
- The solution is also a long line. Should we show them how to do it across lines? Maybe it's actually a bad idea, since the rules on when it's ok / not ok aren't that straightforward. 
- Any particular reason for the `##` instead of `#` in one case?

## 11

- Maybe this is a bit too repetitive?

## 13

- Again, we should show the df.
- Not a big deal but I only had to look at the rows to get the right answer, since only one of the 4 choices had the correct row query (for Question 1).
- Typo: indec -> index
- Formatting: `[0 ,6 ,2]` should be [0, 6, 2]`

## 14

- This is actually fairly confusing: the difference between using `loc` _when the index is integers anyway` vs. using `iloc`. My first reaction to this exercise was, but we already did it with integer indexing! I think we should maybe emphasize this distinction more overall. Maybe we can have an exercise where you have integer indexing and you show that `loc` and `iloc` do the exact same thing? And then maybe another exercise where you have integer indexes but they are not in order (e.g. you sorted the df by some column first) and so then `loc` and `iloc` do different things? These both seem valuable to get at small distinctions. 
- In general, it feels a bit repetitive to do the same exercise 3 times: loc with names, loc with integers, and then iloc with integers.

## 15

- Typo: "various form of injuries"
- Grammar: change comma to period or semicolon before "let's select"
- Typo: missing question mark in hint.

## 17

- Spelling: "occurances". Run spell check?
- I find the "X" thing is confusing, I'd just show the entire thing with `pd.value_counts` in each case. 

## 18

- What do you mean by "most prominent country" ? Most frequent? Should we also teach them how to get this programmatically? By not doing so, might we be creating some bad habits with this exercise? 

## 19

- "in lecture" -> maybe not the right terminology here
- typo: let -> let's
- Note that `sort=True` seems to be the default for `value_counts()`, so no need to specify it
- Again going back to habits, and I don't know the right answer here, but we should consider: do we want them making temp variables all the time like `position_column`? As opposed to `hockey_players["Position"].value_counts(sort = True)`? Maybe we should show them both? Or maybe you're planning for that later in the course? I'm not sure what is the best approach here.

## 21

- I might prefer to have it load canucks.csv and then copy in the couple of lines of code that computes the `position_freq_df` from there. But I don't feel strongly. 
- In the solution, there is no need to have `position_bar` at the end. In fact we should avoid it, because it causes `<matplotlib.axes._subplots.AxesSubplot at 0x7f6460b13810>` to print out, which we don't want. 
- In fact, there is no need to save the plot as an object at all. However, doing so does suppress the printing, which is kind of nice; if we did not save the plot as an object then we'd need to end the line with a `;` to suppress it. Not sure what is best? But I think we should pick an approach that suppresses the printout.

## 22

- typo: extra `.` before 'using"
- should we consider having them divide by 1_000_000 and then labeling the y axis as "Salary (millions)" ? They might not notice, or might be confused by, the little `1e6` and the fact that the salaries seem so low.

General question/comment: are we working on splitting up these into smaller "cells"? And, if so, would it be possible to show solution for only one of the "cells"? That would be super useful, I think - to show the solution to one line on a multi-line exercise. I think being able to split things up would be a huge improvement to the learning experience of these exercises. It means you could also print out the result of your first line of code before starting the next line.

This is looking good - keep it up @hfboyce !
