### ISSUE TITLE
Feedback for Module 2

### ISSUE THREAD

**Issue by hfboyce** [UBC-MDS/MCL-DSCI-011-programming-in-python#18]
Notes: 

- Hopefully this has less spelling and grammar issues than the first go in module 1. I pushed it through Grammarly and a spell checker, so we will see how much it catches. I read through and tried to catch repeat offenses that I committed in module 1. 

- This is without `apply` and `applymap` which we can discuss at the next meeting. 

- I'm so sorry if this sucks up a lot of your time. 

- Tests were not done for this module. 

- Recently I have encountered caching! I would recommending clearing your cookies. for future Module 2 amendments.

**Comment by mgelbart** [comment]
Can you post a link, and also the number of exercises so I can make sure I'm looking at the right version?

**Comment by mgelbart** [comment]
Or maybe a screenshot of the list of exercises, if we're being extra careful?

**Comment by hfboyce** [comment]
Of course! Sorry! 
- [Website  Link](https://mcl-dsci-511-programming-in-python.netlify.app/)
- 25 exercises 
![image](https://user-images.githubusercontent.com/42727648/79912259-98eb0300-83d6-11ea-93de-87345b2f362b.png)
![image](https://user-images.githubusercontent.com/42727648/79912376-cafc6500-83d6-11ea-849e-880fcdb5b47b.png)

**Comment by mgelbart** [comment]
Thanks. Looks like I'm looking at the right version - that's good. Here we go.

- 1.2: No need for code font on `URL`
- 1.3: Can you fix these links so that they open in a new tab/window?
- 1.5: Delete "The character combination is endless to accommodate other txt files."
- 1.7: I don't think "subfile" is standard terminology. What did you mean here? Subdirectory?
- 1.7: In the figure, "Data" should have a lower case "d"
- 1.7: would it be good to show [the repo](https://github.com/UBC-MDS/MCL-DSCI-511-programming-in-python) where they can see the data subdirectory? Or is that extra confusing?
- 1.8: "file" -> "folder" or "directory" ?
- 3: `pokeman_df` -> `pokemon_df`. 
- For both 3 and 4, if I do "show solution" and then "submit" and I get an error. Please check all the exercises for this problem.
- 5: "text file name" -> "Excel file named"
- 6.1: have we defined the term "arguments" at some point?
- 6.3: I would link to this and have them look at the plain text first - I think that'd be really helpful rather than just looking at the corrupted pandas output. Update: Oh, I see you do this on the next slide. I think it'd be better to show this first, even if you still show the corrupted output afterwards. I'm fine with this screenshot or a link to the URL. But maybe the URL is more reproducible?
- 6.4: The commas in the first 2 lines feel a bit unrealistic here. Wouldn't a more realistic scenario be just some free text without those commas?
- 6.7: Remove comma after "Similarly"
- 6.8: "Or we could use the column label in square brackets." -> "Or we could use the column labels, also in square brackets."
- 6.9: I think this would benefit from a more authentic use case. Hmm, have we yet taught anything where this could be useful, like some sort of indexing or filtering or... ? Or should we at least say that it'll be clear later why this is useful? Or maybe we just cut these out of the course? I've never used them personally.
- 8: "pathway" ? Also, the instructions are confusing here. The first bullet point makes it seem like you should read in the entire file. This is further reinforced by the word "entire" in the last bullet point. How about this:
  - Read in the first 100 rows and columns `name`, `total_bs` and `type` from the file `pokemon.csv`, which is located in the `data` directory.
  - Save the resulting dataframe as `pokemon_sample`.
  - Display `pokemon_sample`.

(To be continued)

**Comment by hfboyce** [comment]
Hi @mgelbart!

> For both 3 and 4, if I do "show solution" and then "submit" and I get an error. Please check all the exercises for this problem.

Regarding the submits, I just inserted placeholder files for the tests. I have not written tests yet, for the practice questions in this module. Should I write tests from now on before tagging you to look over them? I was under the impression that I shouldn't be writing any yet. 

In addition to this, note that for all exercises further in this module, the "Submit" button won't be present because I stopped putting placeholder files in the folder for questions. 

Which option would be best?: 
- [ ] A "submit" button present but with working tests 
- [ ] A "submit" button present but with no working tests 
- [ ] No "submit" button and no test

Thank you so much!

**Comment by mgelbart** [comment]
Ah, right. No need to write the tests right now, Elijah will do that. Now that I know, it's fine. Both options 2 or 3 are equally good.

**Comment by mgelbart** [comment]
- 9: See my comments on the instructions for 8. 
- 10.3: "old column name" : "new-column-name" -> let's be consistent with spaces vs. hyphens
- 10.5: for the sake of establishing good habits, should we store that conversion factor in a variable?
- 10.5: "covert" -> "convert"
- 10.6: "1" -> "one"; also "In a similar way to `df.assign()`" -> "While `df.assign()` creates columns,"
- 10.6: ~~it's slightly confusing because in the previous slide you say to always assign the result to an object, but here you don't.~~ Update: oh! this is addressed on the next slide.
- 10.7: "save over" -> "overwrite" ?
- 11.1: I would remove the `df = ` because that's exactly what you're _not_ doing here.
- 13: have they learned this yet, that they can sum columns? What if they first make an actual dataframe with double square brackets: 

```
total_special = pokemon[['sp_attack']] + pokemon[['sp_defense']]
```

does `df.assign` work if you pass in a one-column df instead of a series? If this works, maybe it would be a good 2-part question? 

- 13: in the solution, I believe `columns='deck_no'` needs to be `columns=['deck_no']` ?
- 14.2: did we have the attribution in Module 1 as well?
- 14.3: Maybe we can give an English interpretation of the code, e.g. "get me the rows of `df` where the `df` protein value is greater than 4" ? Maybe that helps clarify why `df` appears twice?
- 14.3: Let's also draw their attention to the results - "Look at the protein column and notice that all values are above 4" or something.
- 14.4: is this their first time seeing `==`? If so, some elaboration might be good. Along the lines of "`=` is for assignment, `==` is for comparison".
- 14.5: Are you sure it's Quakers rather than Quaker?
- 14.6: Although, in Python, `df[ 4 <= df['protein'] <= 5 ]` might work? If this works, I would show it. Regardless, I'd change the example for `&` to be protein >= 4 and mfr==Q. That way they can relate the queries on the previous slides to this slide.
- 14.7: "2" -> "two" (generally standard for numbers below 10, I believe?)
- 14.8: Hmm, I just have a gut feeling that doing one numerical and one categorical will be more clear here. Ideally, it'd be the same query you've already done, but just changing & to |. We can make a comment about how it returned more results this time.
- 14.9: good to show this case of no results.
- 14.10, 14.11: hmm, I wonder if this might be overkill here. It seems unlikely that they'd need this, especially since you can just do multiple lines of code instead of the &. Consider removing?
- 15: I really like this MC question that follows up on the coding. The only question is, do you expect them to use `print`? Or, if not, it's a bit confusing because they are already supposed to display something else.
- 16: Looping back to skills from Module 1 - nice! Is it possible to make hints for the MC question?
- 17: Going back to my earlier comments about the true/false values in `read_csv`, I think this `legendary` thing is a missed opportunity. Because if you do that, you can just index directly with `pokemon['legendary']`. I'm still in favour of taking that stuff out, but if we leave it in then this would be a good opportunity to use it? But also, going back to my comments about 14.10, 14.11, I feel this might be getting to messy. Maybe we instead teach them to do:

```
legendary_pokemon = pokemon[pokemon['legendary'] == 1]
legendary_awesome_pokemon = legendary_pokemon[(legendary_pokemon['total_bs'] > 650) | (legendary_pokemon['speed'] > 140)] 
```

?

(to be continued)

**Comment by mgelbart** [comment]
- 18.2: "After" -> "after"
- 18.3: Need a period after `value_counts()`
- 18.4, 18.5: Hmm, I'm not sure I agree here. You _can_ do `pd.read_csv('cereal.csv')["sugar"].value_counts()` or something like that. The real criterion is that the function/method return an object. You can even chain multiple functions, although the chaining goes right-to-left instead of left-to-right, as in `pd.melt(pd.pivot(df))`. So, I would reframe this to say that it's usually with methods, and that the methods return the object. Update: The current explanation is especially misleading given 18.6, where we chain the filtering, which does not look like a method to the students.
- 18.6: can you show the "old" code for direct comparison on the same slide? You may need to reduce it to 3 steps for this all to fit, that is fine.
- 18.7: I did not even know that was possible, ha. Good to know.
- 18.8 (does not exist): are we missing the ending slide here?
- 19: May need to be redone per earlier comments.
- 20: I like that we provide the formatting with the parentheses. 
- 20: There is some interplay here with my comment about exercise 13. They will need to stay in sync.
- 20: I wonder if we can do something more authentic. As far as I can tell, here the `drop` and `loc` steps don't actually affect the final scatter plot. Can we pick an exercise where all steps are needed for the final result? I do like that the result is a plot though! 
- 21.2: Missing period at end of sentence. Also in 21.4, 21.6.
- 21.2: Maybe as a more gentle introduction, we can start by filtering separately on two cases and showing the results. And then saying that sometimes you want to do things on all the groups and it would be a hassle to do this manually with filtering 7 times, and then do every operation to all 7 groups, etc? We can emphasize that it's incredibly convenient, but technically they could already do all the things with what they knew before.
- 21.3: Great figure. But make it more clear that there are actually more than 2 groups.
- 21.7: Bam, now we see the power of this approach. I would loop back and relish in the convenience here. Have them think about how they'd do this without `groupby`. You could even present this problem at the very start ("How do we get the mean sugars for each manufacturer?").
- 21.9: "On its own, without `groupby`:"
- 21.11: I'm a bit underwhelmed by `agg`. But sure, why not.
- 21.13: Is this overboard? Do we need it?
- One thing that seems missing here is plotting with groupby. Can we show a plot on the groupby object? It works really nicely, you get a separate line for each group, with a legend and everything. You'll need to think of a good case. But for the avocado price analysis I showed you, it was really nice. Here's a screenshot.

![Screen Shot 2020-04-21 at 3 55 40 PM](https://user-images.githubusercontent.com/157368/79922329-92fe1d80-83e8-11ea-898b-229a41c72551.png)

- 22.2: remove comma after "following"
- I found 22.2 confusing. Hmm. Could you show the output as an image and ask which line of code produces that output?
- 23 
  - "save the new dataframe over object `pokemon`." -> "overwrite the `pokemon` object." 
  - pokemon_type -> `pokemon_type`
  - Question refers to `type_means` dataframe, but it isn't defined?
  - Is it necessary to do the `pokemon = pokemon.loc[ : , 'attack': 'type']` step? Maybe remove it? Or, if it's needed, maybe provide this for them to reduce the load here? There are a lot of blanks!
  - For the last part, maybe it would be better to just subset the fire, water, ice rows into a new df and print it, rather than save them in 3 separate variables? 
- 24: Some comments from 23 apply here as well.
- 24: There are some issues with italics in the instructions. I think you need to put those variable names in code font so that the underscores are ignored, e.g. `capture_rt`.
- 25.4: Possible formatting issue with [cereal dataset]

**Comment by hfboyce** [comment]
Thank you for putting in so much time to this! I'll try and go through as much as I can for our meeting tomorrow.

**Comment by mgelbart** [comment]
I think the most important is to read through so we can discuss the tricky bits - no need to make all the changes by tomorrow's meeting.

**Comment by hfboyce** [comment]
## Addressing feedback

>  6.1: have we defined the term "arguments" at some point?
We do a little bit in [Module 1 exercise 3 slide 8](https://mcl-dsci-511-programming-in-python.netlify.app/module1). This is from Tiffany's book. 

> 6.4: The commas in the first 2 lines feel a bit unrealistic here. Wouldn't a more realistic scenario be just some free text without those commas?

This isn't made up! This is what actually happens! see the raw file of the csv file [here](https://raw.githubusercontent.com/UBC-MDS/MCL-DSCI-511-programming-in-python/master/slides/candybars-h.csv)!

> 6.9: I think this would benefit from a more authentic use case. Hmm, have we yet taught anything where this could be useful, like some sort of indexing or filtering or... ? Or should we at least say that it'll be clear later why this is useful? Or maybe we just cut these out of the course? I've never used them personally.

Let's discuss! I am open to taking them out. 

> 9: See my comments on the instructions for 8.

If we take out this content I'll just replace Q9 all together. 

> 13: have they learned this yet, that they can sum columns? What if they first make an actual dataframe with double square brackets:
`total_special = pokemon[['sp_attack']] + pokemon[['sp_defense']]`
does `df.assign` work if you pass in a one-column df instead of a series? If this works, maybe it would be a good 2-part question?

This doesn't work, but I do have a question in we should teach them that we can make new df by adding columns if they can select and slice already? 

> 13: in the solution, I believe columns='deck_no' needs to be columns=['deck_no'] ?

Should I teach standard practice to always include square brackets? In the content right now, if there is only one column, square brackets are not needed. 

> 14.2: did we have the attribution in Module 1 as well?

We do! It was added in a version after your second check! 

>  14.5: Are you sure it's Quakers rather than Quaker?

🤦🏼‍♀️

> 14.6: Although, in Python, df[ 4 <= df['protein'] <= 5 ] might work? If this works, I would show it. Regardless, I'd change the example for & to be protein >= 4 and mfr==Q. That way they can relate the queries on the previous slides to this slide.

[This unfortunately does not work](https://stackoverflow.com/questions/31617845/how-to-select-rows-in-a-dataframe-between-two-values-in-python-pandas/40442778)

> 14.10, 14.11: hmm, I wonder if this might be overkill here. It seems unlikely that they'd need this, especially since you can just do multiple lines of code instead of the &. Consider removing?

Discuss in meeting! 

> 15: I really like this MC question that follows up on the coding. The only question is, do you expect them to use print? Or, if not, it's a bit confusing because they are already supposed to display something else. 

I'm not sure I understand what you mean. 

> 17: Going back to my earlier comments about the true/false values in read_csv, I think this legendary thing is a missed opportunity. Because if you do that, you can just index directly with pokemon['legendary']. I'm still in favour of taking that stuff out, but if we leave it in then this would be a good opportunity to use it? But also, going back to my comments about 14.10, 14.11, I feel this might be getting to messy. Maybe we instead teach them to do:
legendary_pokemon = pokemon[pokemon['legendary'] == 1]
legendary_awesome_pokemon = legendary_pokemon[(legendary_pokemon['total_bs'] > 650) | (legendary_pokemon['speed'] > 140)] 

Discuss taking out multiple conditions and amend this. 

> 18.4, 18.5: Hmm, I'm not sure I agree here. You can do pd.read_csv('cereal.csv')["sugar"].value_counts() or something like that. The real criterion is that the function/method return an object. You can even chain multiple functions, although the chaining goes right-to-left instead of left-to-right, as in pd.melt(pd.pivot(df)). So, I would reframe this to say that it's usually with methods, and that the methods return the object. Update: The current explanation is especially misleading given 18.6, where we chain the filtering, which does not look like a method to the students.

Major discussion here. 

(To be continued in the morning )

**Comment by hfboyce** [comment]
> 23/24 For the last part, maybe it would be better to just subset the fire, water, ice rows into a new df and print it, rather than save them in 3 separate variables?

Which skills would be better to test here, obtaining values from a df or subsetting a df?
